version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - dotnet restore Code/ClientInvestmentsCalculator/ClientInvestmentsCalculator.csproj
  pre_build:
    commands:
      - mkdir -p ./publish
  build:
    commands:
      - dotnet publish Code/ClientInvestmentsCalculator/ClientInvestmentsCalculator.csproj -c Release -o ./publish
      - ls ./publish
artifacts:
  files:
    - '**/*'
  base-directory: ./publish