version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - dotnet restore Code/ClientInvestmentsCalculator/ClientInvestmentsCalculator.csproj
  build:
    commands:
      - dotnet publish Code/ClientInvestmentsCalculator/ClientInvestmentsCalculator.csproj -c Release -o .
      - ls .
artifacts:
  files:
    - '**/*'
  base-directory: .